import { ScoreResult, ScoreBreakdown, CategoryScore } from "@/types/scoring";
import { ParsedResume } from "@/types/resume";

// Mock parsed resume data
const mockParsedResume1: ParsedResume = {
  rawText: "John Doe's resume content...",
  name: "John Doe",
  email: "john.doe@email.com",
  phone: "+1-555-0123",
  location: "San Francisco, CA",
  experience: [
    {
      company: "Acme Corp",
      role: "Senior Front-End Developer",
      startDate: "2019-01",
      endDate: "present",
      duration: "5 years",
      description: "Led development of React applications with TypeScript",
    },
    {
      company: "Tech Startup",
      role: "Front-End Developer",
      startDate: "2017-06",
      endDate: "2018-12",
      duration: "1.5 years",
      description: "Built responsive web applications",
    },
  ],
  education: [
    {
      institution: "State University",
      degree: "B.S.",
      field: "Computer Science",
      graduationDate: "2017",
    },
  ],
  skills: [
    "React",
    "TypeScript",
    "JavaScript",
    "CSS",
    "Tailwind",
    "Jest",
    "Git",
  ],
  keywords: {
    technical: ["React", "TypeScript", "JavaScript", "HTML", "CSS"],
    tools: ["Git", "Webpack", "Vite"],
    frameworks: ["Next.js", "React", "Node.js"],
    soft: ["leadership", "collaboration", "mentoring"],
    testing: ["Jest", "React Testing Library"],
    styling: ["Tailwind CSS", "CSS Modules", "Styled Components"],
  },
  links: {
    github: "https://github.com/johndoe",
    portfolio: "https://johndoe.dev",
    linkedin: "https://linkedin.com/in/johndoe",
    other: [],
  },
  metrics: [
    {
      text: "45% improvement in load time",
      value: 45,
      unit: "%",
      context: "Optimized bundle size leading to 45% improvement in load time",
    },
    {
      text: "Reduced bug count by 60%",
      value: 60,
      unit: "%",
      context: "Implemented comprehensive testing reducing bug count by 60%",
    },
  ],
  fileName: "john_doe.pdf",
  parsedAt: new Date("2025-10-21T10:00:00Z"),
  totalYearsExperience: 6.5,
};

const mockParsedResume2: ParsedResume = {
  rawText: "Jane Smith's resume content...",
  name: "Jane Smith",
  email: "jane.smith@email.com",
  phone: "+1-555-0124",
  location: "Austin, TX",
  experience: [
    {
      company: "Digital Agency",
      role: "Front-End Developer",
      startDate: "2021-03",
      endDate: "present",
      duration: "2 years",
      description: "Developed client websites using React",
    },
  ],
  education: [
    {
      institution: "Coding Bootcamp",
      degree: "Certificate",
      field: "Full-Stack Development",
      graduationDate: "2021",
    },
  ],
  skills: ["React", "JavaScript", "CSS", "HTML", "Git"],
  keywords: {
    technical: ["React", "JavaScript", "HTML", "CSS"],
    tools: ["Git", "npm"],
    frameworks: ["React"],
    soft: ["communication", "problem-solving"],
    testing: [],
    styling: ["CSS", "SCSS"],
  },
  links: {
    github: "https://github.com/janesmith",
    other: [],
  },
  metrics: [],
  fileName: "jane_smith.pdf",
  parsedAt: new Date("2025-10-21T10:05:00Z"),
  totalYearsExperience: 2,
};

const mockParsedResume3: ParsedResume = {
  rawText: "Bob Johnson's resume content...",
  name: "Bob Johnson",
  email: "bob.johnson@email.com",
  location: "New York, NY",
  experience: [
    {
      company: "Tech Giant",
      role: "Staff Front-End Engineer",
      startDate: "2015-06",
      endDate: "present",
      duration: "8 years",
      description: "Lead architect for UI platform",
    },
  ],
  education: [
    {
      institution: "MIT",
      degree: "M.S.",
      field: "Computer Science",
      graduationDate: "2015",
    },
  ],
  skills: [
    "React",
    "TypeScript",
    "JavaScript",
    "CSS",
    "Testing",
    "Architecture",
  ],
  keywords: {
    technical: ["React", "TypeScript", "JavaScript", "GraphQL"],
    tools: ["Git", "Docker", "Jenkins"],
    frameworks: ["Next.js", "React", "Redux"],
    soft: ["leadership", "architecture", "mentoring"],
    testing: ["Jest", "Cypress", "Testing Library"],
    styling: ["CSS-in-JS", "Emotion", "Tailwind"],
  },
  links: {
    github: "https://github.com/bobjohnson",
    portfolio: "https://bobjohnson.com",
    linkedin: "https://linkedin.com/in/bobjohnson",
    other: ["https://medium.com/@bobjohnson"],
  },
  metrics: [
    {
      text: "10x performance improvement",
      value: 10,
      unit: "x",
      context: "Redesigned architecture achieving 10x performance improvement",
    },
  ],
  fileName: "bob_johnson.pdf",
  parsedAt: new Date("2025-10-21T10:10:00Z"),
  totalYearsExperience: 8,
};

// Mock score breakdowns
const mockBreakdown1: ScoreBreakdown = {
  technical: {
    categoryName: "Technical Skills",
    score: 28,
    maxScore: 35,
    percentage: 80,
    subcategories: [
      {
        name: "React + TypeScript + Hooks",
        score: 7,
        maxScore: 7,
        percentage: 100,
        matched: ["React", "TypeScript", "Hooks", "Custom Hooks"],
        reasoning: "Strong evidence of React and TypeScript mastery",
      },
      {
        name: "JavaScript/TypeScript",
        score: 6,
        maxScore: 8,
        percentage: 75,
        matched: ["ES6+", "TypeScript", "Async/Await"],
        reasoning: "Good JS fundamentals, missing some advanced patterns",
      },
      {
        name: "CSS & Styling",
        score: 5,
        maxScore: 5,
        percentage: 100,
        matched: ["Tailwind CSS", "CSS Modules", "Styled Components"],
        reasoning: "Multiple modern CSS approaches demonstrated",
      },
      {
        name: "Testing",
        score: 3,
        maxScore: 4,
        percentage: 75,
        matched: ["Jest", "React Testing Library"],
        reasoning: "Good unit testing, missing E2E experience",
      },
      {
        name: "Tooling",
        score: 3,
        maxScore: 5,
        percentage: 60,
        matched: ["Webpack", "Git", "npm"],
        reasoning: "Basic tooling knowledge, could be stronger",
      },
    ],
  },
  experience: {
    categoryName: "Experience Quality",
    score: 22,
    maxScore: 25,
    percentage: 88,
    subcategories: [
      {
        name: "Years of Experience",
        score: 10,
        maxScore: 10,
        percentage: 100,
        matched: ["5+ years"],
        reasoning: "6.5 years total, 5 years in current role",
      },
      {
        name: "Company Quality",
        score: 7,
        maxScore: 8,
        percentage: 88,
        matched: ["Acme Corp (Tier 2)"],
        reasoning: "Strong company background",
      },
      {
        name: "Role Progression",
        score: 5,
        maxScore: 7,
        percentage: 71,
        matched: ["Senior title"],
        reasoning: "Good progression to Senior level",
      },
    ],
  },
  impact: {
    categoryName: "Impact Indicators",
    score: 12,
    maxScore: 20,
    percentage: 60,
    subcategories: [
      {
        name: "Quantified Achievements",
        score: 8,
        maxScore: 10,
        percentage: 80,
        matched: ["45% improvement", "60% bug reduction"],
        reasoning: "Good use of metrics to show impact",
      },
      {
        name: "Leadership",
        score: 4,
        maxScore: 10,
        percentage: 40,
        matched: ["Led development", "mentoring"],
        reasoning: "Some leadership indicators, could be stronger",
      },
    ],
  },
  portfolio: {
    categoryName: "Portfolio & Links",
    score: 8,
    maxScore: 15,
    percentage: 53,
    subcategories: [
      {
        name: "GitHub",
        score: 5,
        maxScore: 7,
        percentage: 71,
        matched: ["GitHub profile present"],
        reasoning: "Has GitHub link but activity unknown",
      },
      {
        name: "Portfolio Site",
        score: 3,
        maxScore: 5,
        percentage: 60,
        matched: ["Portfolio link"],
        reasoning: "Portfolio site mentioned",
      },
      {
        name: "Open Source",
        score: 0,
        maxScore: 3,
        percentage: 0,
        matched: [],
        reasoning: "No open source contributions mentioned",
      },
    ],
  },
  foundation: {
    categoryName: "Foundation",
    score: 4,
    maxScore: 5,
    percentage: 80,
    subcategories: [
      {
        name: "Education",
        score: 4,
        maxScore: 5,
        percentage: 80,
        matched: ["B.S. Computer Science"],
        reasoning: "Solid CS degree from accredited university",
      },
    ],
  },
};

const mockBreakdown2: ScoreBreakdown = {
  technical: {
    categoryName: "Technical Skills",
    score: 18,
    maxScore: 35,
    percentage: 51,
    subcategories: [
      {
        name: "React + TypeScript + Hooks",
        score: 4,
        maxScore: 7,
        percentage: 57,
        matched: ["React", "Hooks"],
        reasoning: "React experience but no TypeScript",
      },
      {
        name: "JavaScript/TypeScript",
        score: 4,
        maxScore: 8,
        percentage: 50,
        matched: ["ES6+", "JavaScript"],
        reasoning: "Basic JavaScript, missing TypeScript",
      },
      {
        name: "CSS & Styling",
        score: 3,
        maxScore: 5,
        percentage: 60,
        matched: ["CSS", "SCSS"],
        reasoning: "Traditional CSS approaches",
      },
      {
        name: "Testing",
        score: 0,
        maxScore: 4,
        percentage: 0,
        matched: [],
        reasoning: "No testing experience mentioned",
      },
      {
        name: "Tooling",
        score: 2,
        maxScore: 5,
        percentage: 40,
        matched: ["Git", "npm"],
        reasoning: "Basic tools only",
      },
    ],
  },
  experience: {
    categoryName: "Experience Quality",
    score: 12,
    maxScore: 25,
    percentage: 48,
    subcategories: [
      {
        name: "Years of Experience",
        score: 5,
        maxScore: 10,
        percentage: 50,
        matched: ["2 years"],
        reasoning: "Limited professional experience",
      },
      {
        name: "Company Quality",
        score: 4,
        maxScore: 8,
        percentage: 50,
        matched: ["Digital Agency (Tier 4)"],
        reasoning: "Agency experience",
      },
      {
        name: "Role Progression",
        score: 3,
        maxScore: 7,
        percentage: 43,
        matched: ["Front-End Developer"],
        reasoning: "Entry-level role, no progression yet",
      },
    ],
  },
  impact: {
    categoryName: "Impact Indicators",
    score: 6,
    maxScore: 20,
    percentage: 30,
    subcategories: [
      {
        name: "Quantified Achievements",
        score: 0,
        maxScore: 10,
        percentage: 0,
        matched: [],
        reasoning: "No metrics or quantified results",
      },
      {
        name: "Leadership",
        score: 1,
        maxScore: 10,
        percentage: 10,
        matched: [],
        reasoning: "No leadership indicators",
      },
    ],
  },
  portfolio: {
    categoryName: "Portfolio & Links",
    score: 3,
    maxScore: 15,
    percentage: 20,
    subcategories: [
      {
        name: "GitHub",
        score: 3,
        maxScore: 7,
        percentage: 43,
        matched: ["GitHub profile"],
        reasoning: "GitHub link present",
      },
      {
        name: "Portfolio Site",
        score: 0,
        maxScore: 5,
        percentage: 0,
        matched: [],
        reasoning: "No portfolio site",
      },
      {
        name: "Open Source",
        score: 0,
        maxScore: 3,
        percentage: 0,
        matched: [],
        reasoning: "No open source work",
      },
    ],
  },
  foundation: {
    categoryName: "Foundation",
    score: 2,
    maxScore: 5,
    percentage: 40,
    subcategories: [
      {
        name: "Education",
        score: 2,
        maxScore: 5,
        percentage: 40,
        matched: ["Bootcamp Certificate"],
        reasoning: "Bootcamp background, no formal CS degree",
      },
    ],
  },
};

const mockBreakdown3: ScoreBreakdown = {
  technical: {
    categoryName: "Technical Skills",
    score: 33,
    maxScore: 35,
    percentage: 94,
    subcategories: [
      {
        name: "React + TypeScript + Hooks",
        score: 7,
        maxScore: 7,
        percentage: 100,
        matched: ["React", "TypeScript", "Hooks", "Advanced patterns"],
        reasoning: "Exceptional React and TypeScript expertise",
      },
      {
        name: "JavaScript/TypeScript",
        score: 8,
        maxScore: 8,
        percentage: 100,
        matched: ["ES6+", "TypeScript", "Advanced patterns"],
        reasoning: "Master-level JavaScript knowledge",
      },
      {
        name: "CSS & Styling",
        score: 5,
        maxScore: 5,
        percentage: 100,
        matched: ["CSS-in-JS", "Tailwind", "Emotion"],
        reasoning: "Multiple advanced styling approaches",
      },
      {
        name: "Testing",
        score: 4,
        maxScore: 4,
        percentage: 100,
        matched: ["Jest", "Cypress", "Testing Library"],
        reasoning: "Comprehensive testing experience",
      },
      {
        name: "Tooling",
        score: 5,
        maxScore: 5,
        percentage: 100,
        matched: ["Docker", "Jenkins", "Advanced build tools"],
        reasoning: "Strong DevOps and tooling knowledge",
      },
    ],
  },
  experience: {
    categoryName: "Experience Quality",
    score: 25,
    maxScore: 25,
    percentage: 100,
    subcategories: [
      {
        name: "Years of Experience",
        score: 10,
        maxScore: 10,
        percentage: 100,
        matched: ["8+ years"],
        reasoning: "Extensive professional experience",
      },
      {
        name: "Company Quality",
        score: 8,
        maxScore: 8,
        percentage: 100,
        matched: ["Tech Giant (Tier 1)"],
        reasoning: "Top-tier company experience",
      },
      {
        name: "Role Progression",
        score: 7,
        maxScore: 7,
        percentage: 100,
        matched: ["Staff Engineer"],
        reasoning: "Excellent progression to Staff level",
      },
    ],
  },
  impact: {
    categoryName: "Impact Indicators",
    score: 18,
    maxScore: 20,
    percentage: 90,
    subcategories: [
      {
        name: "Quantified Achievements",
        score: 9,
        maxScore: 10,
        percentage: 90,
        matched: ["10x performance improvement"],
        reasoning: "Exceptional quantified impact",
      },
      {
        name: "Leadership",
        score: 9,
        maxScore: 10,
        percentage: 90,
        matched: ["Lead architect", "Platform ownership"],
        reasoning: "Strong technical leadership",
      },
    ],
  },
  portfolio: {
    categoryName: "Portfolio & Links",
    score: 14,
    maxScore: 15,
    percentage: 93,
    subcategories: [
      {
        name: "GitHub",
        score: 7,
        maxScore: 7,
        percentage: 100,
        matched: ["Active GitHub", "Open source contributions"],
        reasoning: "Strong GitHub presence",
      },
      {
        name: "Portfolio Site",
        score: 5,
        maxScore: 5,
        percentage: 100,
        matched: ["Professional portfolio"],
        reasoning: "Excellent portfolio site",
      },
      {
        name: "Open Source",
        score: 2,
        maxScore: 3,
        percentage: 67,
        matched: ["Medium blog"],
        reasoning: "Active in tech community",
      },
    ],
  },
  foundation: {
    categoryName: "Foundation",
    score: 5,
    maxScore: 5,
    percentage: 100,
    subcategories: [
      {
        name: "Education",
        score: 5,
        maxScore: 5,
        percentage: 100,
        matched: ["M.S. Computer Science from MIT"],
        reasoning: "Exceptional educational background",
      },
    ],
  },
};

// Mock score results
export const mockScoreResults: ScoreResult[] = [
  {
    candidateId: "1",
    resumeFileName: "john_doe.pdf",
    totalScore: 74,
    verdict: "strong",
    verdictLabel: "Strong Candidate",
    verdictAction: "Phone Screen",
    verdictEmoji: "🟡",
    breakdown: mockBreakdown1,
    strengths: [
      "Strong TypeScript + React expertise with 5+ years experience",
      "Quantified impact: 45% improvement in load time, 60% bug reduction",
      "Solid CS degree and professional progression",
      "Modern tech stack including Tailwind, Jest, Next.js",
    ],
    concerns: [
      "Limited testing scope - only unit testing with Jest",
      "No E2E testing frameworks mentioned",
      "Portfolio presence could be stronger",
      "Limited open source contributions",
    ],
    extractedData: mockParsedResume1,
    profileUsed: "Front-End Developer",
    scoredAt: new Date("2025-10-21T11:00:00Z"),
    scoredBy: "automated-pass1",
  },
  {
    candidateId: "2",
    resumeFileName: "jane_smith.pdf",
    totalScore: 58,
    verdict: "potential",
    verdictLabel: "Potential",
    verdictAction: "Consider with Reservations",
    verdictEmoji: "🟠",
    breakdown: mockBreakdown2,
    strengths: [
      "React experience from bootcamp and 2 years professional work",
      "GitHub presence shows some code samples",
      "Basic understanding of modern web development",
    ],
    concerns: [
      "No TypeScript experience",
      "Limited professional experience (2 years)",
      "No testing experience mentioned",
      "No quantified achievements or metrics",
      "Bootcamp background without CS fundamentals",
      "Agency experience may mean limited depth",
    ],
    extractedData: mockParsedResume2,
    profileUsed: "Front-End Developer",
    scoredAt: new Date("2025-10-21T11:05:00Z"),
    scoredBy: "automated-pass1",
  },
  {
    candidateId: "3",
    resumeFileName: "bob_johnson.pdf",
    totalScore: 95,
    verdict: "exceptional",
    verdictLabel: "Exceptional Candidate",
    verdictAction: "Priority Interview",
    verdictEmoji: "🟢",
    breakdown: mockBreakdown3,
    strengths: [
      "8 years at top-tier tech company (FAANG-level)",
      "Staff Engineer with proven technical leadership",
      "Master's degree in CS from MIT",
      "10x performance improvement - exceptional quantified impact",
      "Comprehensive testing experience (Jest, Cypress, Testing Library)",
      "Active community presence (blog, open source)",
      "Strong portfolio and GitHub presence",
    ],
    concerns: [
      "May be overqualified for some positions",
      "Likely commands top-tier compensation",
    ],
    extractedData: mockParsedResume3,
    profileUsed: "Front-End Developer",
    scoredAt: new Date("2025-10-21T11:10:00Z"),
    scoredBy: "automated-pass1",
  },
];
